/*1394860853,182630701,JIT Construction: v1162685,en_US*/

/**
 * Copyright Facebook Inc.
 *
 * Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
try {
(function(){var a=window._fbds||(window._fbds={}),b=window._fbq||(window._fbq=[]);function c(i){var j=[];for(var k=0,l=i.length;k<l;k++)j.push(i[k][0]+'='+encodeURIComponent(i[k][1]));return j.join('&');}function d(i,j){var k=function(){if(i.detachEvent){i.detachEvent('onload',k);}else i.onload=null;j();};if(i.attachEvent){i.attachEvent('onload',k);}else i.onload=k;}function e(i,j){var k='fb'+Math.random().toString().replace('.',''),l=document.createElement('form');l.method='post';l.action=i;l.target=k;l.acceptCharset='utf-8';l.style.display='none';var m=document.createElement('iframe');m.src='javascript:false';m.name=k;l.appendChild(m);d(m,function(){for(var n=0,o=j.length;n<o;n++){var p=document.createElement('input');p.name=j[n][0];p.value=j[n][1];l.appendChild(p);}d(m,function(){l.parentNode.removeChild(l);});l.submit();});document.body.appendChild(l);}a.track=function(i,j){if(!a.pixelId)return false;var k=typeof i;if(k!=='string'&&k!=='number')return false;var l=[];l.push(['id',a.pixelId]);l.push(['ev',i]);l.push(['dl',document.location.href]);l.push(['rl',document.referrer]);if(j&&typeof j==='object')for(var m in j)if(j.hasOwnProperty(m)){var n=j[m];if(typeof n in {number:1,string:1,boolean:1})l.push(['cd['+encodeURIComponent(m)+']',n]);}var o='https://www.facebook.com/tr/',p=c(l);if(1024>(o+'?'+p).length){var q=new Image();q.src=o+'?'+p;}else e(o,l);return true;};var f=function(i){if(Object.prototype.toString.call(i)!=='[object Array]')return false;var j=i.shift();if(!j)return false;var k=a[j];if(!k)return false;return k.apply&&k.apply(a,i);};for(var g=0,h=b.length;g<h;++g)f(b[g]);b.push=f;})();} catch (e) {new Image().src="http:\/\/www.facebook.com\/" + 'common/scribe_endpoint.php?c=jssdk_error&m='+encodeURIComponent('{"error":"LOAD", "extra": {"name":"'+e.name+'","line":"'+(e.lineNumber||e.line)+'","script":"'+(e.fileName||e.sourceURL||e.script)+'","stack":"'+(e.stackTrace||e.stack)+'","revision":"1162685","message":"'+e.message+'"}}');}